// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Dewtest;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Dewtest_Roo_Jpa_Entity {
    
    declare @type: Dewtest: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Dewtest.id;
    
    @Version
    @Column(name = "version")
    private Integer Dewtest.version;
    
    public Long Dewtest.getId() {
        return this.id;
    }
    
    public void Dewtest.setId(Long id) {
        this.id = id;
    }
    
    public Integer Dewtest.getVersion() {
        return this.version;
    }
    
    public void Dewtest.setVersion(Integer version) {
        this.version = version;
    }
    
}
