// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.domain;

import com.sut.test.domain.Dewtest;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Dewtest_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Dewtest.entityManager;
    
    public static final List<String> Dewtest.fieldNames4OrderClauseFilter = java.util.Arrays.asList("nameTest");
    
    public static final EntityManager Dewtest.entityManager() {
        EntityManager em = new Dewtest().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Dewtest.countDewtests() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Dewtest o", Long.class).getSingleResult();
    }
    
    public static List<Dewtest> Dewtest.findAllDewtests() {
        return entityManager().createQuery("SELECT o FROM Dewtest o", Dewtest.class).getResultList();
    }
    
    public static List<Dewtest> Dewtest.findAllDewtests(String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Dewtest o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Dewtest.class).getResultList();
    }
    
    public static Dewtest Dewtest.findDewtest(Long id) {
        if (id == null) return null;
        return entityManager().find(Dewtest.class, id);
    }
    
    public static List<Dewtest> Dewtest.findDewtestEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Dewtest o", Dewtest.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    public static List<Dewtest> Dewtest.findDewtestEntries(int firstResult, int maxResults, String sortFieldName, String sortOrder) {
        String jpaQuery = "SELECT o FROM Dewtest o";
        if (fieldNames4OrderClauseFilter.contains(sortFieldName)) {
            jpaQuery = jpaQuery + " ORDER BY " + sortFieldName;
            if ("ASC".equalsIgnoreCase(sortOrder) || "DESC".equalsIgnoreCase(sortOrder)) {
                jpaQuery = jpaQuery + " " + sortOrder;
            }
        }
        return entityManager().createQuery(jpaQuery, Dewtest.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Dewtest.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Dewtest.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Dewtest attached = Dewtest.findDewtest(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Dewtest.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Dewtest.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Dewtest Dewtest.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Dewtest merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
