// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.test.web;

import com.sut.test.domain.Dewtest;
import com.sut.test.web.ApplicationConversionServiceFactoryBean;
import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.core.convert.converter.Converter;
import org.springframework.format.FormatterRegistry;

privileged aspect ApplicationConversionServiceFactoryBean_Roo_ConversionService {
    
    declare @type: ApplicationConversionServiceFactoryBean: @Configurable;
    
    public Converter<Dewtest, String> ApplicationConversionServiceFactoryBean.getDewtestToStringConverter() {
        return new org.springframework.core.convert.converter.Converter<com.sut.test.domain.Dewtest, java.lang.String>() {
            public String convert(Dewtest dewtest) {
                return new StringBuilder().append(dewtest.getNameTest()).toString();
            }
        };
    }
    
    public Converter<Long, Dewtest> ApplicationConversionServiceFactoryBean.getIdToDewtestConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.Long, com.sut.test.domain.Dewtest>() {
            public com.sut.test.domain.Dewtest convert(java.lang.Long id) {
                return Dewtest.findDewtest(id);
            }
        };
    }
    
    public Converter<String, Dewtest> ApplicationConversionServiceFactoryBean.getStringToDewtestConverter() {
        return new org.springframework.core.convert.converter.Converter<java.lang.String, com.sut.test.domain.Dewtest>() {
            public com.sut.test.domain.Dewtest convert(String id) {
                return getObject().convert(getObject().convert(id, Long.class), Dewtest.class);
            }
        };
    }
    
    public void ApplicationConversionServiceFactoryBean.installLabelConverters(FormatterRegistry registry) {
        registry.addConverter(getDewtestToStringConverter());
        registry.addConverter(getIdToDewtestConverter());
        registry.addConverter(getStringToDewtestConverter());
    }
    
    public void ApplicationConversionServiceFactoryBean.afterPropertiesSet() {
        super.afterPropertiesSet();
        installLabelConverters(getObject());
    }
    
}
